import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "@mantine/core/styles.css";
import "@/app/globals.css";

import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import ClientLayout from "./ClientLayout";
import Content from "./Content";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <ClientLayout content={<Content>{children}</Content>} />
        </MantineProvider>
      </body>
    </html>
  );
}
